apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-widget-generator

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: docker.io/ai-widget-generator
    newName: docker.io/ai-widget-generator
    newTag: latest
